" Whitespaces
set listchars=eol:$,tab:>·,trail:~,extends:>,precedes:<
set list
set relativenumber

" spaces instant tab
set tabstop=4
set shiftwidth=4
set expandtab

set ignorecase

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'Raimondi/delimitMate'
Plugin 'scrooloose/nerdtree'
Plugin 'MattesGroeger/vim-bookmarks'

map <c-n> :NERDTreeToggle<CR>

"let g:UltiSnipsExpandTrigger="<tab>"
"let g:UltiSnipsJumpForwardTrigger="<c-b>"
"let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"let g:UltiSnipsEditSplit="vertical"


call vundle#end()
filetype plugin indent on
